version: "2"
linters:
  enable:
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
    - zerologlint
  settings:
      gocyclo:
          min-complexity: 10
      goconst:
          min-occurrences: 3
      staticcheck:
        checks: ["all", "-ST1003", "-ST1005"]
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Exclude gosec from running on tests files.
      - path: _test\.go
        linters:
          - gosec
          - revive
      - path: migration/ocpmigrations/mig_(.+)\.go
        linters:
          - revive
      - path: types/
        linters:
          - revive
formatters:
  enable:
    - gofmt
    - goimports