{
 "title": "CCX Redis",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "ccx-data-pipeline-stage,ccx-data-pipeline-prod"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"ccx-redis.*\", container!=\"\"}[1m])) by (pod, container)",
     "legendFormat": "{{pod}}: {{container}}"
    }
   ]
  },
  {
   "title": "Pod Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"ccx-redis.*\", container!=\"\"}) by (pod, container)",
     "legendFormat": "{{pod}}: {{container}}"
    }
   ]
  },
  {
   "title": "Max Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Commands / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{namespace=\"$namespace\"} [1m])) by (cmd)",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Total Time Spent by Command / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{namespace=\"$namespace\"}[1m])) by (cmd) != 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Average Time Spent by Command / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{namespace=\"$namespace\"}[1m])) by (cmd)\n  /\nsum(irate(redis_commands_total{namespace=\"$namespace\"}[1m])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=\"$namespace\"}) by (db, instance)",
     "legendFormat": "{{ db }}, {{ instance }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_net_input_bytes_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "sum(rate(redis_net_output_bytes_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{namespace=\"$namespace\"}",
     "legendFormat": "used, {{ instance }}"
    },
    {
     "expr": "redis_memory_max_bytes{namespace=\"$namespace\"}",
     "legendFormat": "max, {{ instance }}"
    }
   ]
  },
  {
   "title": "Connected/Blocked Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_clients{namespace=\"$namespace\"})",
     "legendFormat": "connected"
    },
    {
     "expr": "sum(redis_blocked_clients{namespace=\"$namespace\"})",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "Expired/Evicted Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{namespace=\"$namespace\"}[5m])) by (instance)",
     "legendFormat": "expired, {{ instance }}"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{namespace=\"$namespace\"}[5m])) by (instance)",
     "legendFormat": "evicted, {{ instance }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=\"$namespace\"}) by (instance) - sum (redis_db_keys_expiring{namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "not expiring, {{ instance }}"
    },
    {
     "expr": "sum (redis_db_keys_expiring{namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "expiring, {{ instance }}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instannamespace=\"$namespace\"}[5m])",
     "legendFormat": "hits, {{ instance }}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{namespace=\"$namespace\"}[5m])",
     "legendFormat": "misses, {{ instance }}"
    }
   ]
  }
 ]
}