name: BDD Tests

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  bdd:
    name: BDD tests
    uses: RedHatInsights/processing-tools/.github/workflows/bdd.yaml@v0.4.4
    with:
      service: dvo-writer
      use_kafka: true
      use_postgres: true
