# Set as automatically merge all the pull requests created by dependabot[bot]
name: Dependabot auto-merge
on: pull_request

# This section adds write permissions to the secrets.GITHUB_TOKEN. Default is just read
permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Github Actions bot approves the PR
        run: gh pr review --approve "$PR_URL"
        env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: InsightsDroid approves the PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.INSIGHTSDROID_TOKEN}}
      - name: Enable auto-merge for Dependabot PRs
        # We can filter depending on the semver major, minor, or patch updates,
        # but let's not do it for now
        # if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}